import type { DetectedTechnology } from './types.js';
import { httpRequest } from '../../core/http-client.js';

/**
 * WAF detection signatures.
 * Each WAF is identified by specific response characteristics when
 * a suspicious/malicious payload is sent.
 */
interface WafSignature {
  name: string;
  /** Response headers that indicate this WAF */
  headerPatterns: { key: string; pattern: RegExp }[];
  /** Status codes commonly returned by this WAF when blocking */
  blockStatusCodes?: number[];
  /** Body patterns in WAF block pages */
  bodyPatterns?: RegExp[];
}

const WAF_SIGNATURES: WafSignature[] = [
  {
    name: 'Cloudflare',
    headerPatterns: [
      { key: 'cf-ray', pattern: /.+/ },
      { key: 'server', pattern: /cloudflare/i },
    ],
    blockStatusCodes: [403, 503],
    bodyPatterns: [/Attention Required.*Cloudflare/i, /cf-error-details/i],
  },
  {
    name: 'AWS WAF',
    headerPatterns: [
      { key: 'x-amzn-waf', pattern: /.+/ },
    ],
    blockStatusCodes: [403],
    bodyPatterns: [/Request blocked/i],
  },
  {
    name: 'Akamai Kona',
    headerPatterns: [
      { key: 'server', pattern: /AkamaiGHost/i },
      { key: 'x-akamai-transformed', pattern: /.+/ },
    ],
    blockStatusCodes: [403],
    bodyPatterns: [/Access Denied.*Reference/i],
  },
  {
    name: 'Sucuri',
    headerPatterns: [
      { key: 'x-sucuri-id', pattern: /.+/ },
      { key: 'server', pattern: /Sucuri/i },
    ],
    blockStatusCodes: [403],
    bodyPatterns: [/sucuri\.net/i, /Access Denied.*Sucuri/i],
  },
  {
    name: 'Imperva Incapsula',
    headerPatterns: [
      { key: 'x-cdn', pattern: /Imperva|Incapsula/i },
    ],
    blockStatusCodes: [403],
    bodyPatterns: [/Incapsula incident/i, /powered by Incapsula/i],
  },
  {
    name: 'ModSecurity',
    headerPatterns: [
      { key: 'server', pattern: /mod_security|NOYB/i },
    ],
    blockStatusCodes: [403, 406],
    bodyPatterns: [/ModSecurity/i, /This error was generated by Mod_Security/i],
  },
  {
    name: 'F5 BIG-IP ASM',
    headerPatterns: [
      { key: 'server', pattern: /BIG-IP|BigIP/i },
    ],
    blockStatusCodes: [403],
    bodyPatterns: [/The requested URL was rejected/i],
  },
  {
    name: 'Fortinet FortiWeb',
    headerPatterns: [
      { key: 'server', pattern: /FortiWeb/i },
    ],
    blockStatusCodes: [403],
    bodyPatterns: [/FortiWeb/i, /\.fwb\b/i],
  },
  {
    name: 'Barracuda',
    headerPatterns: [
      { key: 'server', pattern: /Barracuda/i },
    ],
    blockStatusCodes: [403],
    bodyPatterns: [/Barracuda/i],
  },
  {
    name: 'DenyAll',
    headerPatterns: [
      { key: 'server', pattern: /DenyAll/i },
    ],
    blockStatusCodes: [403],
    bodyPatterns: [/Condition Intercepted/i],
  },
  {
    name: 'Wordfence',
    headerPatterns: [],
    bodyPatterns: [/wordfence/i, /generated by Wordfence/i],
  },
  {
    name: 'Comodo WAF',
    headerPatterns: [
      { key: 'server', pattern: /Comodo/i },
    ],
    blockStatusCodes: [403],
  },
];

/**
 * Detects Web Application Firewalls (WAFs) protecting the target.
 *
 * Strategy:
 * 1. First check existing response headers for WAF indicators
 * 2. Send a harmless but suspicious-looking request to trigger WAF
 * 3. Analyze the WAF's response signature
 */
export async function detectWaf(
  targetUrl: string,
  existingHeaders: Record<string, string | string[] | undefined>
): Promise<DetectedTechnology[]> {
  const detected: DetectedTechnology[] = [];

  // ─── Phase 1: Check existing response headers ────
  for (const waf of WAF_SIGNATURES) {
    for (const { key, pattern } of waf.headerPatterns) {
      const headerVal = existingHeaders[key.toLowerCase()];
      const value = Array.isArray(headerVal) ? headerVal.join(', ') : headerVal;
      if (value && pattern.test(value)) {
        addWafDetection(detected, waf.name, 90, `Header [${key}]: ${value}`);
        break;
      }
    }
  }

  // ─── Phase 2: Probe with a safe suspicious payload ────
  try {
    // Append a harmless XSS-like parameter to trigger WAF
    const probeUrl = new URL(targetUrl);
    probeUrl.searchParams.set('test', '<script>alert(1)</script>');

    const response = await httpRequest(probeUrl.toString(), {
      timeout: 10_000,
    });

    for (const waf of WAF_SIGNATURES) {
      // Skip if already detected with high confidence
      if (detected.find((d) => d.name === waf.name && d.confidence >= 90)) continue;

      // Check response headers from probe
      for (const { key, pattern } of waf.headerPatterns) {
        const headerVal = response.headers[key.toLowerCase()];
        const value = Array.isArray(headerVal) ? headerVal.join(', ') : headerVal;
        if (value && pattern.test(value)) {
          addWafDetection(detected, waf.name, 85, `Probe header [${key}]: ${value}`);
          break;
        }
      }

      // Check if status code matches WAF blocking pattern
      if (waf.blockStatusCodes?.includes(response.statusCode)) {
        // Check body for WAF-specific error pages
        if (waf.bodyPatterns) {
          for (const bodyPattern of waf.bodyPatterns) {
            if (bodyPattern.test(response.body)) {
              addWafDetection(
                detected,
                waf.name,
                85,
                `Block page detected (HTTP ${response.statusCode}): ${bodyPattern.source.slice(0, 40)}`
              );
              break;
            }
          }
        }
      }
    }
  } catch {
    // Probe failed — that's OK, we still have phase 1 results
  }

  return detected;
}

function addWafDetection(
  detected: DetectedTechnology[],
  name: string,
  confidence: number,
  evidence: string
): void {
  const existing = detected.find((d) => d.name === name);
  if (existing) {
    if (confidence > existing.confidence) {
      existing.confidence = confidence;
      existing.evidence = evidence;
    }
  } else {
    detected.push({
      name,
      category: 'waf',
      confidence,
      evidence,
    });
  }
}
